apiVersion: v1
kind: Service
metadata:
  name: game-logic
  namespace: gameim
  labels:
    app: logic
spec:
  type: NodePort
  ports:
    - port: 9001
      protocol: TCP
      targetPort: 9001
      #nodePort: 31363
  selector:
    run: logic-app001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: logic
  name: logic
  namespace: gameim
spec:
  replicas: 1
  selector:
    matchLabels:
      run: gameim-logic
  template:
    metadata:
    spec:
      containers:
        - image: ${IMAGE}
          name: gameim-bench
          command: [ "/app/bench" ]
          args: ["-conf","/app/conf/bench.yaml"]
          resources:
            requests:
              memory: "1024Mi"
              cpu: "1000m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          imagePullPolicy: Always
          volumeMounts:
            - name: gameim-logic-conf
              mountPath: "/app/conf/logic.yaml"
      volumes:
        - name: gameim-bench-conf
          configMap:
            name: gameim-bench-conf
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: comet-logic
  namespace: pg
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gameim-logic
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
