apiVersion: v1
kind: Service
metadata:
  name: logic-app001
  namespace: pg
  labels:
    app: logic-app001
spec:
  type: NodePort
  ports:
    - port: 9001
      protocol: TCP
      targetPort: 9001
  selector:
    run: logic-app001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: logic-app001
  name: logic-app001
  namespace: pg
spec:
  replicas: 2
  selector:
    matchLabels:
      run: logic-app001
  template:
    metadata:
      labels:
        run: logic-app001
        app: logic-app001
        kratos-service-id: "56991810-c77f-4a95-8190-393efa9c1a61"
        kratos-service-app: "logic-app001"
        kratos-service-version: "0.0.1"
      annotations:
        kratos-service-protocols: |
          {"80": "http"}
        kratos-service-metadata: |
          {"region": "sh", "zone": "sh001", "cluster": "pd"}
    spec:
      containers:
        - image: ${IMAGE}
          name: logic-app001
          command: [ "/app/logic" ]
          args: ["-conf","/app/conf/logic.yaml"]
          resources:
            requests:
              memory: "1024Mi"
              cpu: "1000m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"


