apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nsq-001
  name: nsq-001
  namespace: gameim
spec:
  replicas: 2
  selector:
    matchLabels:
      run: logic-app001
  template:
    metadata:
      labels:
        run: logic-app001
        app: logic-app001
    spec:
      containers:
        - image: nsqio/nsq
          name: nsq-001
          command: [ "/app/logic" ]
          args: ["-conf","/app/conf/logic.yaml"]
          resources:
            requests:
              memory: "1024Mi"
              cpu: "1000m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          imagePullPolicy: Always
          volumeMounts:
            - name: gameim-conf
              mountPath: "/app/conf"
      volumes:
        - name: gameim-conf
          configMap:
            name: gameim-conf