apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-nsq-nsqd-0
  namespace: gameim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-ceph-block
